name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.2
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-test-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-test-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0
          elixir-version: 1.14.0
      - run: mix deps.get
      - run: MIX_ENV=test mix test
